### ISSUE TITLE
Unit module

### ISSUE THREAD

**Issue by rxaviers** [johnnyreilly/globalize-so-what-cha-want#3]
Hi!

We're about to merge support for unit formatting: https://github.com/jquery/globalize/pull/512

It would be great if globalize-so-what-cha-want could be updated to also support it.

Thanks

**Comment by johnnyreilly** [comment]
Will do @rxaviers!

**Comment by johnnyreilly** [comment]
Resolved by https://github.com/johnnyreilly/globalize-so-what-cha-want/commit/03cae2d1d761d901adf74b218c2522b133d6331a

**Comment by rxaviers** [comment]
:clap: thanks
