### ISSUE TITLE
What cldr-data urls to use from cldr-data npm package

### ISSUE THREAD

**Issue by franciclo** [johnnyreilly/globalize-so-what-cha-want#7]
Hi, i find this tool very useful, but i can't find anywhere what specific cldr-data urls to download, i find the [default list](https://github.com/rxaviers/cldr-data-npm/blob/master/urls.json) to be very large and includes a lot of resources my project don't need.
Could this tool provide a subset of cldr-data urls to add in the `cldr-data-urls-json` package.json property  for use of the npm cldr-data package?

**Comment by johnnyreilly** [comment]
It probably could but I'm not actively working on it at the minute. If you wanted to implement that in a PR I'd happily take it though!

**Comment by franciclo** [comment]
How could i know what json file is needed for each module?
Currently i remove all urls and added one by one until i get no errors 😄 this was easy since i only needed the message module but there must be a better way.

**Comment by franciclo** [comment]
Sorry, that question was more suitable for the cldr-data-npm repository, i should get an answer over there and after i learn why it is how it is, maybe come back and make a PR, thank you for your time!
